version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos/restaurant-management/
hooks:
  ApplicationStop:
    - location: backend/scripts/stop_server.sh
      timeout: 300
      runas: centos

  AfterInstall:
    - location: backend/scripts/install_dependencies.sh
      timeout: 300
      runas: centos

  ApplicationStart:
    - location: backend/scripts/start_server.sh
      timeout: 300
      runas: centos
