version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos/
hooks:
  AfterInstall:
    - location: backend/scripts/install_dependencies.sh
      timeout: 300
      runas: centos

  ApplicationStart:
    - location: backend/scripts/start_server.sh
      timeout: 300
      runas: centos
