version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos/restaurant-management/
hooks:
  ApplicationStop:
    - location: backend/scripts/application_stop.sh
      timeout: 300
      runas: centos

  BeforeInstall:
    - location: backend/scripts/before_install.sh
      timeout: 300
      runas: centos

  AfterInstall:
    - location: backend/scripts/after_install.sh
      timeout: 300
      runas: centos

  ApplicationStart:
    - location: backend/scripts/application_start.sh
      timeout: 300
      runas: centos
